language: ruby
rvm:
- 2.3.3

install:
  - gem install jekyll
  - gem install jekyll-mermaid

script:
  - jekyll build

deploy:
  on:
    branch: master
  provider: s3
  bucket: jarospisak.com
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-west-2
  acl: public_read
  skip_cleanup: true
  local_dir: ./_site
