language: ruby
rvm:
- 2.6

install:
  - gem install jekyll

script:
  - jekyll build
  - pip install --user awscli

deploy:
  on:
    branch: master
  provider: s3
  bucket: www.jarospisak.com
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-west-2
  acl: public_read
  skip_cleanup: true
  local_dir: ./_site

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $WWW_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  - aws cloudfront create-invalidation --distribution-id $NON_WWW_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
